name: MelissaMGreen
favicon: null
layout_spectrum: 0.72871
typography_spectrum: 0.05477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-73659126-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#d79f80'
    - '#02799c'
    - '#01bae1'
    - '#f4e6e6'
  brandStrength: 0.4375
  lightness: 0.3125
  saturation: 0.875
  rhythmicContrast: 0.25
purpose: []
