name: MelissaMGreen
favicon: null
layout_spectrum: 0.40694
typography_spectrum: 0.6462876803707331
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#171111'
    - '#524a40'
    - '#faf3df'
    - '#7f7569'
    - '#a9a08f'
  brandStrength: 0.8125
  lightness: 0.25
  saturation: 0.75
  rhythmicContrast: 0.25
purpose: []
